build: reenable ABI compliance checker
Signed-off-by: Cameron Nemo <camerontnorman@gmail.com>

diff --git a/lib/run_abi_checker.sh.in b/lib/run_abi_checker.sh.in
--- a/lib/run_abi_checker.sh.in
+++ b/lib/run_abi_checker.sh.in
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/sh
 #---------------------------------------------------------------------
 # Script to run abi-compliance-checker to ensure ABI not broken.
 #---------------------------------------------------------------------
@@ -20,10 +20,10 @@
 #
 #---------------------------------------------------------------------
 
-die()
-{
-    msg="$*"
-    echo "ERROR: $msg" >&2
+set -eu
+
+die() {
+    printf 'ERR: %s' "$1" >&2
     exit 1
 }
 
@@ -35,43 +35,32 @@ libupstart_libtool="@libupstart@"
 lib_prefix="${libupstart_libtool%.la}"
 libupstart_lt_version="@libupstart_version@"
 old_abi="@abi_official@"
+adump="@abi_dumper@"
 
 # convert libtool(1) version to dotted form
 dotted_version=$(echo "$libupstart_lt_version"|tr ':' '.')
 
 libupstart_path="$build_dir/$libupstart_libtool"
 
-echo "Checking ABI for $lib_prefix"
-echo
+printf 'Checking ABI for %s\n\n' "$lib_prefix"
 
 for file in "$libupstart_path" "$old_abi"
 do
-    [ -f "$file" ] || die "file $file not found"
+	[ -f "$file" ] || die "file $file not found"
 done
 
 # Install the library to a temporary location since we need the
 # full path to the shared library to pass to abi-compliance-checker.
-install_dir=$(mktemp -d --tmpdir="$build_dir")
-[ -z "$install_dir" ] && \
-	die "failed to create temporary install directory"
-
+install_dir="$(mktemp -d --tmpdir="$build_dir")"
 libtool --mode=install install \
     "$libupstart_libtool" "$install_dir" >/dev/null 2>&1
-
-abi_dump_dir=$(mktemp -d --tmpdir="$build_dir")
-[ -z "$abi_dump_dir" ] && \
-	die "failed to create temporary dump directory"
-
-abi_dump_path="$abi_dump_dir/${lib_prefix}_${dotted_version}.abi.tar.gz"
-
 installed_so="$install_dir/$(echo "$lib_prefix"|cut -d\. -f1).so"
-
 [ -f "$installed_so" ] || die "cannot find $installed_so"
 
 # generate a descriptor for the newly-built library version
-"$acc" -library "$lib_prefix" -dump "$acc_descriptor" -dump-path "$abi_dump_path"
-
+abi_dump_dir="$(mktemp -d --tmpdir="$build_dir")"
 new_abi="$abi_dump_dir/${lib_prefix}_${dotted_version}.abi.tar.gz"
+"${adump}" "${installed_so}" -o "${new_abi}"
 [ -f "$new_abi" ] || die "cannot find $new_abi"
 
 # run the ABI checker
@@ -80,8 +69,4 @@ new_abi="$abi_dump_dir/${lib_prefix}_${dotted_version}.abi.tar.gz"
 # clean up
 libtool --mode=uninstall \
     rm "$install_dir/$libupstart_libtool" >/dev/null 2>&1
-
-rm -rf "$abi_dump_dir" "$build_dir/logs" "$install_dir"
-
-# HTML report generated by $acc
-rm -rf compat_reports/
+rm -rf -- "$abi_dump_dir" "$build_dir/logs" "$install_dir"
